# Generated by Django 6.0.7 on 2026-07-12 06:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('shipmentjson', models.JSONField(blank=True, null=True)),
                ('shipmenttracking', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=32, unique=True)),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=255)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('seller', models.CharField(blank=True, default='', max_length=255)),
                ('courier', models.CharField(default='-', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('amount', models.CharField(blank=True, default='', max_length=50)),
                ('warehouse', models.CharField(blank=True, default='', max_length=255)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('awb', models.CharField(db_index=True, default='-', max_length=100)),
                ('codpaidstatus', models.CharField(default='Pending', max_length=50)),
                ('platform', models.CharField(choices=[('Manual', 'Manual'), ('Amazon', 'Amazon'), ('Shopify', 'Shopify'), ('WooCommerce', 'WooCommerce'), ('Custom', 'Custom'), ('Merged', 'Merged')], default='Manual', max_length=20)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('address_line1', models.CharField(blank=True, default='', max_length=500)),
                ('address_line2', models.CharField(blank=True, default='', max_length=500)),
                ('landmark', models.CharField(blank=True, default='', max_length=255)),
                ('zone', models.CharField(blank=True, default='', max_length=50)),
                ('chargecor', models.CharField(blank=True, default='', max_length=50)),
                ('total_items', models.IntegerField(default=0)),
                ('total_weight', models.FloatField(blank=True, null=True)),
                ('total_volumetric_weight', models.FloatField(blank=True, null=True)),
                ('shopify_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('financial_status', models.CharField(choices=[('paid', 'paid'), ('partially_paid', 'partially_paid'), ('pending', 'pending'), ('refunded', 'refunded'), ('voided', 'voided')], default='pending', max_length=20)),
                ('fulfillment_status', models.CharField(choices=[('fulfilled', 'fulfilled'), ('partial', 'partial'), ('pending', 'pending'), ('restocked', 'restocked'), ('null', 'null')], default='pending', max_length=20)),
                ('payment_gateway', models.CharField(default='manual', max_length=100)),
                ('dispute_status', models.CharField(blank=True, default='', max_length=100)),
                ('dispute_reason', models.CharField(blank=True, default='', max_length=500)),
                ('merge_status', models.CharField(blank=True, default='', max_length=100)),
                ('merge_order', models.JSONField(blank=True, null=True)),
                ('dispute_file', models.CharField(blank=True, default='', max_length=500)),
                ('previousweight', models.CharField(blank=True, default='', max_length=50)),
                ('claimweight', models.CharField(blank=True, default='', max_length=50)),
                ('subtotal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_shipping_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('tracking_history', models.JSONField(blank=True, null=True)),
                ('shipping_address', models.JSONField(blank=True, null=True)),
                ('billing_address', models.JSONField(blank=True, null=True)),
                ('customer_data', models.JSONField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('delivered_time', models.TimeField(blank=True, null=True)),
                ('ndrreason', models.CharField(blank=True, default='', max_length=500)),
                ('trackingnumber', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('gst_rate', models.FloatField(default=18)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('dead_weight', models.FloatField(blank=True, null=True)),
                ('volumetric_weight', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
    ]
