# Generated by Django 6.0.7 on 2026-07-12 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transid', models.CharField(blank=True, default='', max_length=255)),
                ('order_number', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('rto', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet',
                'ordering': ['-created_at'],
            },
        ),
    ]
